### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by elishawest** [jackweatherford/spotify-friend-activity#11]
I am unable to see the entirety of my friend's listening. I checked with several friends to ask if they had the settings on that would allow me to see, and each and everyone did. I am only able to see my mothers listening and I'm not very impressed with her music.

**To Reproduce**
1. Open Spotify
2. Look to the right of the screen and only one person's listening feed from several days ago is there even after refreshing.
3. See an error

What I expected to happen was all of my friends whom I follow to pop up at the right of the screen. But however, they did not.

- Operating System: [e.g. Windows]
- Screen Resolution: [e.g. 1920x1080]
- Chrome Version: [e.g. 98]
![image](https://user-images.githubusercontent.com/114174406/191797073-3137350c-9124-4340-b569-80838c5f7119.png)
that's my screenshot, but i feel my problem is pretty simple.

**Comment by jackweatherford** [comment]
Unfortunately Spotify only provides activity data about Spotify desktop app users - so when a user is active on the web app - their listening data does not get picked up by this extension.
