### ISSUE TITLE
Port to Firefox [ENHANCEMENT]

### ISSUE THREAD

**Issue by davidfromtheworld** [jackweatherford/spotify-friend-activity#12]
Hi!, just courious. will there ever be a firefox port of this extension? I've tried the extension and loved it, since I use the spotify website usually, but I am an FF user...

**Comment by jackweatherford** [comment]
I just branched out a version of the code that works as a Firefox Add-on and submitted it to Firefox for review.

You can either wait a few days for Firefox to review and accept the add-on (I'll comment here with the link when it's accepted) or follow the steps [here](https://github.com/jackweatherford/spotify-friend-activity/releases/tag/v1.0.12) to install the add-on manually. (Scroll down to the Firefox section)

**Comment by jackweatherford** [comment]
Firefox has approved the add-on, you can install it [here](https://addons.mozilla.org/addon/spotify-friend-activity/).
