### ISSUE TITLE
[BUG] Activity hides main view

### ISSUE THREAD

**Issue by TheBlapse** [jackweatherford/spotify-friend-activity#15]
The container of the friend's activity displays above the page loaded by spotify hence the content is getting hidden beneath it

![image](https://user-images.githubusercontent.com/76247922/230770424-942d17b2-76aa-4b42-bcd7-43f7b9317562.png)

**Comment by jackweatherford** [comment]
This is a result of Spotify changing their internal styling.
I pushed a fix for this bug [here](https://github.com/jackweatherford/spotify-friend-activity/commit/8962dbb1eccb314a5ac2eb273eea15795cda3b44) and submitted it for review to the Chrome Web Store.
The Chrome Web Store review process takes some time - while waiting for the new version to publish, you can follow the steps [here](https://github.com/jackweatherford/spotify-friend-activity/releases/tag/v1.0.13) to install it manually.

**Comment by jackweatherford** [comment]
The fix is now published to the Chrome Web Store. Ensure you're running version 1.0.13.
