### ISSUE TITLE
[BUG] Missing activity

### ISSUE THREAD

**Issue by kaumii** [jackweatherford/spotify-friend-activity#20]
The issue I am experiencing is that it won't load my friends activity. To reproduce, there is no way I can describe how to reproduce the issue because all I did was use it a few times and now it stopped working, when it should show my friend's activity. The bar that is usually on the side is not appearing.

- Operating System: [Windows]
- Screen Resolution: [1920x1080]

**Comment by jackweatherford** [comment]
Thank you for reporting the issue.
I pushed a fix [here](https://github.com/jackweatherford/spotify-friend-activity/commit/2049eac548f91b266f14e722a0cdb0bab50cbd7a) and submitted it for review to the Chrome Web Store.
The Chrome Web Store review process takes some time - while waiting for the new version to publish, you can follow the steps [here](https://github.com/jackweatherford/spotify-friend-activity/releases/tag/v1.0.14) to install it manually.

**Comment by jackweatherford** [comment]
The fix is now published to the Chrome Web Store. Please update to version 1.0.14.
