### ISSUE TITLE
[BUG] Missing activity

### ISSUE THREAD

**Issue by jaywernnn** [jackweatherford/spotify-friend-activity#21]
The Spotify friend activity feature keeps disappearing after a prolonged period of time and i have to manually switch it on and off again.

**Comment by jackweatherford** [comment]
The fix is now published to the Chrome Web Store. Please update to version 1.0.14.

**Comment by ghost** [comment]
still not working, are you sure its fixed?
i tried both versions from github and chrome web store

**Comment by jackweatherford** [comment]
> still not working, are you sure its fixed? i tried both versions from github and chrome web store

Is the friend activity panel completely gone? Or can you see it and its just empty?

**Comment by ghost** [comment]
![image](https://github.com/jackweatherford/spotify-friend-activity/assets/126506341/e9193fec-e5f3-4bd3-a204-5c35ced4718e)
completely gone

**Comment by jackweatherford** [comment]
> completely gone

Thank you for the screenshot, it made me realize I did not account for the user's selected language for the fix in v1.0.14.
I pushed a new fix [here](https://github.com/jackweatherford/spotify-friend-activity/commit/d939b38ff96b07b69deeb4c5c0e067d8e8f675f2) and submitted it for review to the Chrome Web Store.
The Chrome Web Store review process takes some time - while waiting for the new version to publish, you can follow the steps [here](https://github.com/jackweatherford/spotify-friend-activity/releases/tag/v1.0.15) to install v1.0.15 manually.

**Comment by jackweatherford** [comment]
The fix is now published to the Chrome Web Store. Please ensure you're running version 1.0.16.
