### ISSUE TITLE
[BUG] Missing activity

### ISSUE THREAD

**Issue by keullalalkoh** [jackweatherford/spotify-friend-activity#22]
Missing activity

**Comment by jackweatherford** [comment]
Thank you for reporting the issue.
I pushed a fix [here](https://github.com/jackweatherford/spotify-friend-activity/commit/fabd981f9161b6b44484badfe4beba3f729a7529) and submitted it for review as v1.0.16 to the Chrome Web Store.
The Chrome Web Store review process takes some time - while waiting for the new version to publish, you can follow the steps [here](https://github.com/jackweatherford/spotify-friend-activity/releases/tag/v1.0.16) to install v1.0.16 manually.

**Comment by jackweatherford** [comment]
The fix is now published to the Chrome Web Store. Please ensure you're running version 1.0.16.
