### ISSUE TITLE
[BUG] Missing activity

### ISSUE THREAD

**Issue by holaaa1** [jackweatherford/spotify-friend-activity#25]
**Describe the bug**
i cant see the activity of my friends in spotify

**Comment by holaaa1** [comment]
Despite having downloaded the Spotify friends activity extension, I can't see my friends' activity when I enter the application. i have a chromebook

**Comment by jackweatherford** [comment]
Thank you for the report and sorry for the issue.
I submitted a [fix](https://github.com/jackweatherford/spotify-friend-activity/commit/fabd981f9161b6b44484badfe4beba3f729a7529) to the Chrome Web Store as version 1.0.16.
The Chrome Web Store review process takes some time - while waiting for the new version to publish, you can follow the steps [here](https://github.com/jackweatherford/spotify-friend-activity/releases/tag/v1.0.16) to install version 1.0.16 manually.

**Comment by jackweatherford** [comment]
The fix is now published to the Chrome Web Store. Please ensure you're running version 1.0.16.
