### ISSUE TITLE
[BUG] Friend activity not showing up 

### ISSUE THREAD

**Issue by thanofoz1995** [jackweatherford/spotify-friend-activity#26]
![Screenshot 2023-05-15 10 23 38 AM](https://github.com/jackweatherford/spotify-friend-activity/assets/133679455/17225d26-f350-4357-ae4f-b264db46bc30)
Friend activity is not showing up on the side.

**Comment by jackweatherford** [comment]
Thank you for the report and sorry for the issue.
I submitted a [fix](https://github.com/jackweatherford/spotify-friend-activity/commit/fabd981f9161b6b44484badfe4beba3f729a7529) to the Chrome Web Store as version 1.0.16.
The Chrome Web Store review process takes some time - while waiting for the new version to publish, you can follow the steps [here](https://github.com/jackweatherford/spotify-friend-activity/releases/tag/v1.0.16) to install version 1.0.16 manually.

**Comment by jackweatherford** [comment]
The fix is now published to the Chrome Web Store. Please ensure you're running version 1.0.16.
