### ISSUE TITLE
[BUG] Page layout

### ISSUE THREAD

**Issue by A-LIAM** [jackweatherford/spotify-friend-activity#3]
**Description**

When I turn on the extension, the layout of the web player gets messy, just like in the picture.
![image](https://user-images.githubusercontent.com/96947790/179228248-91efd677-55d0-42c8-b25f-ac38d2690adc.png)

I do not know what caused it to happen, so I don't know how to reproduce it. When I turn off the extension, everything is fine.

**Environment**

- Operating System: Windows 11
- Screen Resolution: 1920x1080 + 1600*900 (Dual Monitor) (Turning off one monitor does not affect the outcome)
- Chrome Version: Version 103.0.5060.114 (Official Build) (64-bit)

**Additional context**

I have other extensions installed interacting with the web player. I turned them off and tried but the issue is still there. So I don't think this issue has any relation to those.

**Comment by jackweatherford** [comment]
The hotfix is now published to the Chrome Web Store.
Instructions on how to get the update are [here](https://github.com/jackweatherford/spotify-friend-activity/issues/6#issuecomment-1186596526).
