### ISSUE TITLE
[BUG] Friend activity stops showing due to token expiring

### ISSUE THREAD

**Issue by turtleship69** [jackweatherford/spotify-friend-activity#31]
**Describe the bug**
After a while of having the activity bar open it stops showing anything, because the token has expired. In the console, the extension logs that no token has been provided, however the request to the [buddylist url](https://guc-spclient.spotify.com/presence-view/v1/buddylist) has the response `Token expired`

**To Reproduce**

1. Have the list open 
2. Wait a while, and the accounts on the list disappear. 

**Expected behavior**
When the token from [here](https://open.spotify.com/get_access_token?reason=transport&productType=web_player) expires, it gets refreshed. 

**Screenshots**

**Environment (please complete the following information):**

- Operating System: Windows
- Screen Resolution: 1920x1080 with 125% scale
- Chrome Version: 114.0.5735.199 (Official Build) (64-bit) (cohort: Stable) 

**Additional context**
Either reloading or disabling and reenabling friend activity makes accounts show up again.

**Comment by jackweatherford** [comment]
Thank you for the report.
I submitted a [fix](https://github.com/jackweatherford/spotify-friend-activity/commit/7d1cb57398d10f86e4bf02ee38465ef97d60975c) to the Chrome Web Store as version 1.0.17.
The Chrome Web Store review process takes some time - while waiting for the new version to publish, you can follow the steps [here](https://github.com/jackweatherford/spotify-friend-activity/releases/tag/v1.0.17) to install version 1.0.17 manually.

**Comment by jackweatherford** [comment]
The fix is now published to the Chrome Web Store. Please ensure you're running version 1.0.17.
