### ISSUE TITLE
[BUG] Friend activity covering header

### ISSUE THREAD

**Issue by Lucinous301** [jackweatherford/spotify-friend-activity#32]
**Describe the bug**
Covers profile and settings

**To Reproduce**
Literally whenever I open spotify

**Expected behavior**
To see my Profile/Settings/Notifications.

**Screenshots**
![Extension_OFF](https://github.com/jackweatherford/spotify-friend-activity/assets/72426503/f79245af-bbd2-4b7b-af61-2691aa8367f2)
![Extension_ON](https://github.com/jackweatherford/spotify-friend-activity/assets/72426503/65a493aa-0463-4c4f-a669-24ebb73d545c)
**Environment (please complete the following information):**

- Operating System: Chrome OS
- Screen Resolution: 1536 x 864
- Chrome Version: 118.0.5993.86

**Additional context**
None

**Comment by jackweatherford** [comment]
Thanks for reporting this issue.
The [fix](https://github.com/jackweatherford/spotify-friend-activity/commit/ea826849d7e27af00b00078604fbd9dd26d4e962) is in the new version 1.0.18.
The Chrome Web Store review process takes some time - while waiting for the new version to publish, you can follow the steps [here](https://github.com/jackweatherford/spotify-friend-activity/releases/tag/v1.0.18) to install version 1.0.18 manually.

**Comment by jackweatherford** [comment]
The fix is now published to the Chrome Web Store. Please ensure you're running version 1.0.18.
