### ISSUE TITLE
[BUG] Friend Activity Not Showing Up

### ISSUE THREAD

**Issue by thanofoz1995** [jackweatherford/spotify-friend-activity#38]
![image](https://github.com/user-attachments/assets/9f020318-86cb-44da-8b8d-9b160ded7f27)

With a recent update with Spotify, the friend activity is not working

**Comment by jackweatherford** [comment]
Thank you for the report and sorry for the issue.
I submitted a [fix](https://github.com/jackweatherford/spotify-friend-activity/commit/ec66089f148d3af5b193bfe799395a359cc73bd6) to the Chrome Web Store as version 1.1.0.
The Chrome Web Store review process takes some time - while waiting for the new version to publish, you can follow the steps [here](https://github.com/jackweatherford/spotify-friend-activity/releases/tag/v1.1.0) to install version 1.1.0 manually.

**Comment by jackweatherford** [comment]
The fix is now published to the Chrome Web Store. Please ensure you're running version 1.1.0.
