### ISSUE TITLE
Friend Activity is not working AGAIN 

### ISSUE THREAD

**Issue by thanofoz1995** [jackweatherford/spotify-friend-activity#39]
Log in: ![Screenshot 2024-08-22 12 30 50 AM](https://github.com/user-attachments/assets/f24f38b4-366f-477b-8cae-b231dc6122c2)

While logged in: ![image](https://github.com/user-attachments/assets/08327d42-e679-47b1-8ee6-375e9cbc9675)

_The friend activity works fine when I open up Spotify, but when I log in...nothing shows up_

**Comment by jackweatherford** [comment]
Fix is in progress - see [this comment](https://github.com/jackweatherford/spotify-friend-activity/issues/38#issuecomment-2308959382)

**Comment by jackweatherford** [comment]
The fix is now published to the Chrome Web Store. Please ensure you're running version 1.1.0.
