### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vanillanga** [jackweatherford/spotify-friend-activity#5]
Spotify will glitch on my ASUS Chromebook if I enable the Spotify Friend Activity extension. Once I turn on the extension, my Spotify will glitch and leave a huge dark space where I cannot access anything. 

1. I go to https://open.spotify.com/ 
2. Log in
3. Enable Spotify Friend Activity to show friend activity
4. See error happen

I expect Spotify to work normally with the Spotify Friend Activity extension as it has been working normally up until two days ago where it glitched and will not go back to normal after I clear cache, clear web browser data, restart my device, powerwash my device, clear cookies, and try reinstalling and logging in several times. 

**Screenshots**
![Screenshot 2022-07-16 5 31 38 PM](https://user-images.githubusercontent.com/109425600/179359180-df57471b-5b65-48dd-bb0e-4ea374929bb9.png)
em.
![Screenshot 2022-07-16 5 32 30 PM](https://user-images.githubusercontent.com/109425600/179359192-328ba2e3-029f-43ef-8159-3be3cead8999.png)

- Operating System: ASUS Chromebook Google ChromeOS
- Version 103.0.5060.114 (Official Build) (64-bit)

**Comment by jackweatherford** [comment]
This is a result of Spotify changing their internal styling - which broke the styling of the Friend Activity panel.
I pushed a hotfix for this bug [here](https://github.com/jackweatherford/spotify-friend-activity/commit/cdad70e9e2df455797ad0ac8c68373e9b8bae5c3) and submitted it for review to the Chrome Web Store.
The Chrome Web Store review process takes some time - while waiting for the hotfix to publish, you can follow the steps [here](https://github.com/jackweatherford/spotify-friend-activity/issues/6) to install the new version manually.

**Comment by jackweatherford** [comment]
The hotfix is now published to the Chrome Web Store.
Instructions on how to get the update are [here](https://github.com/jackweatherford/spotify-friend-activity/issues/6#issuecomment-1186596526).
